# Generated by Django 6.0 on 2026-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.BigIntegerField(default=0),
        ),
    ]
